-- H2 2.3.232; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '217468eb237bd221' HASH 'af7d52c680db0025b857e4c549011d0b97d2bf14593638e7331e92f921b5adcf' ADMIN;          
CREATE CACHED TABLE "public"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);           
ALTER TABLE "public"."flyway_schema_history" ADD CONSTRAINT "public"."flyway_schema_history_pk" PRIMARY KEY("installed_rank"); 
-- 5 +/- SELECT COUNT(*) FROM public.flyway_schema_history;    
INSERT INTO "public"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'sa', TIMESTAMP '2026-07-30 19:53:52.502899', 0, TRUE),
(1, '1', 'create identity tables', 'SQL', 'V1__create_identity_tables.sql', 2098535164, 'sa', TIMESTAMP '2026-07-30 19:53:52.509091', 2, TRUE),
(2, '2', 'create task tables', 'SQL', 'V2__create_task_tables.sql', 1770822585, 'sa', TIMESTAMP '2026-07-30 19:53:52.513144', 2, TRUE),
(3, '3', 'create sampling execution tables', 'SQL', 'V3__create_sampling_execution_tables.sql', -1161371419, 'sa', TIMESTAMP '2026-07-30 19:53:52.517527', 2, TRUE),
(4, '4', 'create audit tables', 'SQL', 'V4__create_audit_tables.sql', 597546131, 'sa', TIMESTAMP '2026-07-30 19:53:52.521305', 2, TRUE);   
CREATE INDEX "public"."flyway_schema_history_s_idx" ON "public"."flyway_schema_history"("success" NULLS FIRST);
CREATE CACHED TABLE "public"."app_user"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "username" CHARACTER VARYING(100) NOT NULL,
    "password_hash" CHARACTER VARYING(255) NOT NULL,
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);       
ALTER TABLE "public"."app_user" ADD CONSTRAINT "public"."CONSTRAINT_4" PRIMARY KEY("id");      
-- 0 +/- SELECT COUNT(*) FROM public.app_user; 
CREATE CACHED TABLE "public"."app_role"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "role_name" CHARACTER VARYING(100) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);        
ALTER TABLE "public"."app_role" ADD CONSTRAINT "public"."CONSTRAINT_45" PRIMARY KEY("id");     
-- 0 +/- SELECT COUNT(*) FROM public.app_role; 
CREATE CACHED TABLE "public"."user_role"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);          
ALTER TABLE "public"."user_role" ADD CONSTRAINT "public"."CONSTRAINT_1" PRIMARY KEY("id");     
-- 0 +/- SELECT COUNT(*) FROM public.user_role;
CREATE INDEX "public"."idx_user_role_user" ON "public"."user_role"("user_id" NULLS FIRST);     
CREATE INDEX "public"."idx_user_role_role" ON "public"."user_role"("role_id" NULLS FIRST);     
CREATE CACHED TABLE "public"."validation_task"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "external_key" CHARACTER VARYING(255) NOT NULL,
    "database_name" CHARACTER VARYING(255) NOT NULL,
    "table_name" CHARACTER VARYING(255) NOT NULL,
    "status" CHARACTER VARYING(50) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);          
ALTER TABLE "public"."validation_task" ADD CONSTRAINT "public"."CONSTRAINT_F" PRIMARY KEY("id");               
-- 0 +/- SELECT COUNT(*) FROM public.validation_task;          
CREATE INDEX "public"."idx_validation_task_status" ON "public"."validation_task"("status" NULLS FIRST);        
CREATE CACHED TABLE "public"."task_run"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "run_id" CHARACTER VARYING(64) NOT NULL,
    "validation_task_id" BIGINT NOT NULL,
    "status" CHARACTER VARYING(50) NOT NULL,
    "target_sample_rows" BIGINT NOT NULL,
    "sampled_rows" BIGINT DEFAULT 0 NOT NULL,
    "final_sql" CHARACTER VARYING,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);          
ALTER TABLE "public"."task_run" ADD CONSTRAINT "public"."CONSTRAINT_E" PRIMARY KEY("id");      
-- 0 +/- SELECT COUNT(*) FROM public.task_run; 
CREATE INDEX "public"."idx_task_run_validation_task" ON "public"."task_run"("validation_task_id" NULLS FIRST); 
CREATE INDEX "public"."idx_task_run_status" ON "public"."task_run"("status" NULLS FIRST);      
CREATE CACHED TABLE "public"."sampling"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "task_run_id" BIGINT NOT NULL,
    "partition_name" CHARACTER VARYING(255) NOT NULL,
    "status" CHARACTER VARYING(50) NOT NULL,
    "planned_rows" BIGINT NOT NULL,
    "sampled_rows" BIGINT DEFAULT 0 NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
); 
ALTER TABLE "public"."sampling" ADD CONSTRAINT "public"."CONSTRAINT_7" PRIMARY KEY("id");      
-- 0 +/- SELECT COUNT(*) FROM public.sampling; 
CREATE INDEX "public"."idx_sampling_task_run" ON "public"."sampling"("task_run_id" NULLS FIRST);               
CREATE CACHED TABLE "public"."shard_task"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "shard_id" CHARACTER VARYING(100) NOT NULL,
    "sampling_id" BIGINT NOT NULL,
    "partition_group" CHARACTER VARYING(1000),
    "status" CHARACTER VARYING(50) NOT NULL,
    "planned_rows" INTEGER NOT NULL,
    "sampled_rows" BIGINT DEFAULT 0 NOT NULL,
    "attempt_count" INTEGER DEFAULT 0 NOT NULL,
    "result_collected" BOOLEAN DEFAULT FALSE NOT NULL,
    "final_sql" CHARACTER VARYING,
    "message" CHARACTER VARYING(2000),
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);    
ALTER TABLE "public"."shard_task" ADD CONSTRAINT "public"."CONSTRAINT_9" PRIMARY KEY("id");    
-- 0 +/- SELECT COUNT(*) FROM public.shard_task;               
CREATE INDEX "public"."idx_shard_task_sampling" ON "public"."shard_task"("sampling_id" NULLS FIRST);           
CREATE INDEX "public"."idx_shard_task_status" ON "public"."shard_task"("status" NULLS FIRST);  
CREATE CACHED TABLE "public"."task_log"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "log_id" CHARACTER VARYING(64) NOT NULL,
    "task_run_id" BIGINT NOT NULL,
    "logged_at" TIMESTAMP NOT NULL,
    "level" CHARACTER VARYING(20) NOT NULL,
    "message" CHARACTER VARYING(4000) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);         
ALTER TABLE "public"."task_log" ADD CONSTRAINT "public"."CONSTRAINT_E7" PRIMARY KEY("id");     
-- 0 +/- SELECT COUNT(*) FROM public.task_log; 
CREATE INDEX "public"."idx_task_log_task_run_logged_at" ON "public"."task_log"("task_run_id" NULLS FIRST, "logged_at" NULLS FIRST);            
CREATE CACHED TABLE "public"."audit_event"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "task_run_id" BIGINT NOT NULL,
    "event_type" CHARACTER VARYING(100) NOT NULL,
    "actor" CHARACTER VARYING(100) NOT NULL,
    "occurred_at" TIMESTAMP NOT NULL,
    "details" CHARACTER VARYING,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "version" BIGINT DEFAULT 0 NOT NULL
);             
ALTER TABLE "public"."audit_event" ADD CONSTRAINT "public"."CONSTRAINT_3" PRIMARY KEY("id");   
-- 0 +/- SELECT COUNT(*) FROM public.audit_event;              
CREATE INDEX "public"."idx_audit_event_task_run_occurred_at" ON "public"."audit_event"("task_run_id" NULLS FIRST, "occurred_at" NULLS FIRST);  
ALTER TABLE "public"."task_run" ADD CONSTRAINT "public"."uk_task_run_run_id" UNIQUE NULLS DISTINCT ("run_id"); 
ALTER TABLE "public"."user_role" ADD CONSTRAINT "public"."uk_user_role" UNIQUE NULLS DISTINCT ("user_id", "role_id");          
ALTER TABLE "public"."task_log" ADD CONSTRAINT "public"."uk_task_log_log_id" UNIQUE NULLS DISTINCT ("log_id"); 
ALTER TABLE "public"."validation_task" ADD CONSTRAINT "public"."uk_validation_task_external_key" UNIQUE NULLS DISTINCT ("external_key");       
ALTER TABLE "public"."shard_task" ADD CONSTRAINT "public"."uk_shard_task_shard_id" UNIQUE NULLS DISTINCT ("shard_id");         
ALTER TABLE "public"."sampling" ADD CONSTRAINT "public"."uk_sampling_task_run_partition" UNIQUE NULLS DISTINCT ("task_run_id", "partition_name");              
ALTER TABLE "public"."app_role" ADD CONSTRAINT "public"."uk_app_role_name" UNIQUE NULLS DISTINCT ("role_name");
ALTER TABLE "public"."app_user" ADD CONSTRAINT "public"."uk_app_user_username" UNIQUE NULLS DISTINCT ("username");             
ALTER TABLE "public"."task_run" ADD CONSTRAINT "public"."fk_task_run_validation_task" FOREIGN KEY("validation_task_id") REFERENCES "public"."validation_task"("id") NOCHECK;   
ALTER TABLE "public"."user_role" ADD CONSTRAINT "public"."fk_user_role_role" FOREIGN KEY("role_id") REFERENCES "public"."app_role"("id") NOCHECK;              
ALTER TABLE "public"."sampling" ADD CONSTRAINT "public"."fk_sampling_task_run" FOREIGN KEY("task_run_id") REFERENCES "public"."task_run"("id") NOCHECK;        
ALTER TABLE "public"."shard_task" ADD CONSTRAINT "public"."fk_shard_task_sampling" FOREIGN KEY("sampling_id") REFERENCES "public"."sampling"("id") NOCHECK;    
ALTER TABLE "public"."user_role" ADD CONSTRAINT "public"."fk_user_role_user" FOREIGN KEY("user_id") REFERENCES "public"."app_user"("id") NOCHECK;              
ALTER TABLE "public"."task_log" ADD CONSTRAINT "public"."fk_task_log_task_run" FOREIGN KEY("task_run_id") REFERENCES "public"."task_run"("id") NOCHECK;        
ALTER TABLE "public"."audit_event" ADD CONSTRAINT "public"."fk_audit_event_task_run" FOREIGN KEY("task_run_id") REFERENCES "public"."task_run"("id") NOCHECK;  
